# fstab generation. crypttab uses the luks keyslot; ssd tmp handling default.
---
mountOptions:
    default: noatime
    btrfs: noatime,compress=zstd:1,space_cache=v2
    btrfs_swap: noatime

ssdExtraMountOptions:
    ext4: discard
    btrfs: discard=async

crypttabOptions: luks

tmpOptions:
    default:
        tmpfs: false
        options: ""
    ssd:
        tmpfs: true
        options: "defaults,noatime,mode=1777"
